/* eslint-disable */
import * as types from './graphql.js';



/**
 * Map of all GraphQL operations in the project.
 *
 * This map has several performance disadvantages:
 * 1. It is not tree-shakeable, so it will include all operations in the project.
 * 2. It is not minifiable, so the string of a GraphQL query will be multiple times inside the bundle.
 * 3. It does not support dead code elimination, so it will add unused operations.
 *
 * Therefore it is highly recommended to use the babel or swc plugin for production.
 * Learn more about it here: https://the-guild.dev/graphql/codegen/plugins/presets/preset-client#reducing-bundle-size
 */
type Documents = {
    "fragment IssueAncestors on Issue {\n  parent {\n    number\n    title\n    body\n    labels(first: 20) {\n      nodes {\n        name\n      }\n    }\n    issueType {\n      name\n    }\n    parent {\n      number\n      title\n      body\n      labels(first: 20) {\n        nodes {\n          name\n        }\n      }\n      issueType {\n        name\n      }\n      parent {\n        number\n        parent {\n          number\n          parent {\n            number\n          }\n        }\n      }\n    }\n  }\n}\n\nquery IssueParents($owner: String!, $name: String!, $number: Int!) {\n  repository(owner: $owner, name: $name) {\n    issue(number: $number) {\n      ...IssueAncestors\n    }\n  }\n}": typeof types.IssueAncestorsFragmentDoc,
    "query IssueNodeId($owner: String!, $name: String!, $number: Int!) {\n  repository(owner: $owner, name: $name) {\n    issue(number: $number) {\n      id\n    }\n  }\n}\n\nquery IssueCreateRefs($owner: String!, $name: String!, $parent: Int!, $withParent: Boolean!) {\n  repository(owner: $owner, name: $name) {\n    id\n    labels(first: 100) {\n      nodes {\n        id\n        name\n      }\n    }\n    parent: issue(number: $parent) @include(if: $withParent) {\n      id\n    }\n  }\n}\n\nquery IssuePlan($owner: String!, $name: String!, $number: Int!) {\n  repository(owner: $owner, name: $name) {\n    owner {\n      id\n    }\n    issue(number: $number) {\n      id\n      number\n      title\n      body\n      labels(first: 20) {\n        nodes {\n          name\n        }\n      }\n      issueType {\n        name\n      }\n      parent {\n        number\n        title\n        body\n        labels(first: 20) {\n          nodes {\n            name\n          }\n        }\n        issueType {\n          name\n        }\n        parent {\n          number\n          title\n          body\n          labels(first: 20) {\n            nodes {\n              name\n            }\n          }\n          issueType {\n            name\n          }\n          parent {\n            number\n            parent {\n              number\n              parent {\n                number\n              }\n            }\n          }\n        }\n      }\n      projectItems(first: 20) {\n        nodes {\n          id\n          project {\n            id\n            number\n            owner {\n              id\n            }\n            field(name: \"Status\") {\n              __typename\n              ... on ProjectV2SingleSelectField {\n                id\n                options {\n                  id\n                  name\n                }\n              }\n            }\n          }\n          status: fieldValueByName(name: \"Status\") {\n            __typename\n            ... on ProjectV2ItemFieldSingleSelectValue {\n              name\n            }\n          }\n        }\n      }\n    }\n  }\n}": typeof types.IssueNodeIdDocument,
    "query PlanItems($login: String!, $number: Int!, $cursor: String) {\n  user(login: $login) {\n    projectV2(number: $number) {\n      items(first: 100, after: $cursor) {\n        pageInfo {\n          hasNextPage\n          endCursor\n        }\n        nodes {\n          status: fieldValueByName(name: \"Status\") {\n            __typename\n            ... on ProjectV2ItemFieldSingleSelectValue {\n              name\n            }\n          }\n          content {\n            __typename\n            ... on Issue {\n              number\n              title\n              url\n              state\n              updatedAt\n              repository {\n                name\n                owner {\n                  login\n                }\n              }\n              labels(first: 20) {\n                nodes {\n                  name\n                }\n              }\n              assignees(first: 10) {\n                nodes {\n                  login\n                }\n              }\n              issueType {\n                name\n              }\n              parent {\n                number\n                parent {\n                  number\n                  parent {\n                    number\n                  }\n                }\n              }\n              subIssuesSummary {\n                total\n                completed\n              }\n              blockedBy(first: 20) {\n                nodes {\n                  number\n                  state\n                }\n              }\n              closedByPullRequestsReferences(first: 10, includeClosedPrs: true) {\n                nodes {\n                  number\n                }\n              }\n            }\n          }\n        }\n      }\n    }\n  }\n}": typeof types.PlanItemsDocument,
    "mutation CreatePlanProject($ownerId: ID!, $title: String!) {\n  createProjectV2(input: {ownerId: $ownerId, title: $title}) {\n    projectV2 {\n      id\n      number\n      url\n      title\n      field(name: \"Status\") {\n        __typename\n        ... on ProjectV2SingleSelectField {\n          id\n          options {\n            id\n            name\n            color\n            description\n          }\n        }\n      }\n    }\n  }\n}\n\nmutation SetStatusOptions($fieldId: ID!, $options: [ProjectV2SingleSelectFieldOptionInput!]!) {\n  updateProjectV2Field(input: {fieldId: $fieldId, singleSelectOptions: $options}) {\n    projectV2Field {\n      __typename\n      ... on ProjectV2SingleSelectField {\n        id\n        options {\n          id\n          name\n        }\n      }\n    }\n  }\n}\n\nmutation LinkPlanRepository($projectId: ID!, $repositoryId: ID!) {\n  linkProjectV2ToRepository(\n    input: {projectId: $projectId, repositoryId: $repositoryId}\n  ) {\n    repository {\n      id\n    }\n  }\n}\n\nmutation CreatePlanIssue($repositoryId: ID!, $title: String!, $body: String!, $labelIds: [ID!], $parentIssueId: ID) {\n  createIssue(\n    input: {repositoryId: $repositoryId, title: $title, body: $body, labelIds: $labelIds, parentIssueId: $parentIssueId}\n  ) {\n    issue {\n      id\n      number\n      url\n    }\n  }\n}\n\nmutation AddPlanBlocker($issueId: ID!, $blockingIssueId: ID!) {\n  addBlockedBy(input: {issueId: $issueId, blockingIssueId: $blockingIssueId}) {\n    issue {\n      id\n    }\n  }\n}\n\nmutation AddPlanLabels($labelableId: ID!, $labelIds: [ID!]!) {\n  addLabelsToLabelable(input: {labelableId: $labelableId, labelIds: $labelIds}) {\n    clientMutationId\n  }\n}\n\nmutation AddPlanSubIssue($issueId: ID!, $subIssueId: ID!) {\n  addSubIssue(input: {issueId: $issueId, subIssueId: $subIssueId}) {\n    issue {\n      id\n    }\n  }\n}\n\nmutation CreatePlanLabel($repositoryId: ID!, $name: String!, $color: String!, $description: String!) {\n  createLabel(\n    input: {repositoryId: $repositoryId, name: $name, color: $color, description: $description}\n  ) {\n    label {\n      id\n    }\n  }\n}\n\nmutation AddPlanItem($projectId: ID!, $contentId: ID!) {\n  addProjectV2ItemById(input: {projectId: $projectId, contentId: $contentId}) {\n    item {\n      id\n    }\n  }\n}\n\nmutation SetPlanStatus($projectId: ID!, $itemId: ID!, $fieldId: ID!, $optionId: String!) {\n  updateProjectV2ItemFieldValue(\n    input: {projectId: $projectId, itemId: $itemId, fieldId: $fieldId, value: {singleSelectOptionId: $optionId}}\n  ) {\n    projectV2Item {\n      id\n    }\n  }\n}": typeof types.CreatePlanProjectDocument,
    "query PlanOwnerIds($login: String!, $owner: String!, $name: String!) {\n  user(login: $login) {\n    id\n  }\n  repository(owner: $owner, name: $name) {\n    id\n  }\n}\n\nquery PlanProject($login: String!, $number: Int!) {\n  user(login: $login) {\n    projectV2(number: $number) {\n      id\n      number\n      url\n      title\n      field(name: \"Status\") {\n        __typename\n        ... on ProjectV2SingleSelectField {\n          id\n          options {\n            id\n            name\n          }\n        }\n      }\n    }\n  }\n}": typeof types.PlanOwnerIdsDocument,
    "query PullRequestSnapshot($owner: String!, $name: String!, $number: Int!) {\n  repository(owner: $owner, name: $name) {\n    pullRequest(number: $number) {\n      number\n      title\n      isDraft\n      additions\n      deletions\n      changedFiles\n      updatedAt\n      url\n      headRefOid\n      headRefName\n      state\n      merged\n      mergeable\n      reviewDecision\n      commits(last: 1) {\n        nodes {\n          commit {\n            statusCheckRollup {\n              state\n              contexts(first: 100) {\n                nodes {\n                  __typename\n                  ... on CheckRun {\n                    databaseId\n                    name\n                    status\n                    conclusion\n                    detailsUrl\n                  }\n                  ... on StatusContext {\n                    context\n                    state\n                    targetUrl\n                  }\n                }\n              }\n            }\n          }\n        }\n      }\n      reviews(last: 50) {\n        nodes {\n          databaseId\n          state\n          body\n          submittedAt\n          author {\n            login\n          }\n          commit {\n            oid\n          }\n        }\n      }\n      reviewThreads(first: 100) {\n        nodes {\n          isResolved\n          comments(first: 1) {\n            nodes {\n              databaseId\n              author {\n                login\n              }\n              body\n              path\n              line\n              url\n            }\n          }\n        }\n      }\n      comments(last: 50) {\n        nodes {\n          author {\n            login\n          }\n          body\n          url\n        }\n      }\n    }\n  }\n}": typeof types.PullRequestSnapshotDocument,
};
const documents: Documents = {
    "fragment IssueAncestors on Issue {\n  parent {\n    number\n    title\n    body\n    labels(first: 20) {\n      nodes {\n        name\n      }\n    }\n    issueType {\n      name\n    }\n    parent {\n      number\n      title\n      body\n      labels(first: 20) {\n        nodes {\n          name\n        }\n      }\n      issueType {\n        name\n      }\n      parent {\n        number\n        parent {\n          number\n          parent {\n            number\n          }\n        }\n      }\n    }\n  }\n}\n\nquery IssueParents($owner: String!, $name: String!, $number: Int!) {\n  repository(owner: $owner, name: $name) {\n    issue(number: $number) {\n      ...IssueAncestors\n    }\n  }\n}": types.IssueAncestorsFragmentDoc,
    "query IssueNodeId($owner: String!, $name: String!, $number: Int!) {\n  repository(owner: $owner, name: $name) {\n    issue(number: $number) {\n      id\n    }\n  }\n}\n\nquery IssueCreateRefs($owner: String!, $name: String!, $parent: Int!, $withParent: Boolean!) {\n  repository(owner: $owner, name: $name) {\n    id\n    labels(first: 100) {\n      nodes {\n        id\n        name\n      }\n    }\n    parent: issue(number: $parent) @include(if: $withParent) {\n      id\n    }\n  }\n}\n\nquery IssuePlan($owner: String!, $name: String!, $number: Int!) {\n  repository(owner: $owner, name: $name) {\n    owner {\n      id\n    }\n    issue(number: $number) {\n      id\n      number\n      title\n      body\n      labels(first: 20) {\n        nodes {\n          name\n        }\n      }\n      issueType {\n        name\n      }\n      parent {\n        number\n        title\n        body\n        labels(first: 20) {\n          nodes {\n            name\n          }\n        }\n        issueType {\n          name\n        }\n        parent {\n          number\n          title\n          body\n          labels(first: 20) {\n            nodes {\n              name\n            }\n          }\n          issueType {\n            name\n          }\n          parent {\n            number\n            parent {\n              number\n              parent {\n                number\n              }\n            }\n          }\n        }\n      }\n      projectItems(first: 20) {\n        nodes {\n          id\n          project {\n            id\n            number\n            owner {\n              id\n            }\n            field(name: \"Status\") {\n              __typename\n              ... on ProjectV2SingleSelectField {\n                id\n                options {\n                  id\n                  name\n                }\n              }\n            }\n          }\n          status: fieldValueByName(name: \"Status\") {\n            __typename\n            ... on ProjectV2ItemFieldSingleSelectValue {\n              name\n            }\n          }\n        }\n      }\n    }\n  }\n}": types.IssueNodeIdDocument,
    "query PlanItems($login: String!, $number: Int!, $cursor: String) {\n  user(login: $login) {\n    projectV2(number: $number) {\n      items(first: 100, after: $cursor) {\n        pageInfo {\n          hasNextPage\n          endCursor\n        }\n        nodes {\n          status: fieldValueByName(name: \"Status\") {\n            __typename\n            ... on ProjectV2ItemFieldSingleSelectValue {\n              name\n            }\n          }\n          content {\n            __typename\n            ... on Issue {\n              number\n              title\n              url\n              state\n              updatedAt\n              repository {\n                name\n                owner {\n                  login\n                }\n              }\n              labels(first: 20) {\n                nodes {\n                  name\n                }\n              }\n              assignees(first: 10) {\n                nodes {\n                  login\n                }\n              }\n              issueType {\n                name\n              }\n              parent {\n                number\n                parent {\n                  number\n                  parent {\n                    number\n                  }\n                }\n              }\n              subIssuesSummary {\n                total\n                completed\n              }\n              blockedBy(first: 20) {\n                nodes {\n                  number\n                  state\n                }\n              }\n              closedByPullRequestsReferences(first: 10, includeClosedPrs: true) {\n                nodes {\n                  number\n                }\n              }\n            }\n          }\n        }\n      }\n    }\n  }\n}": types.PlanItemsDocument,
    "mutation CreatePlanProject($ownerId: ID!, $title: String!) {\n  createProjectV2(input: {ownerId: $ownerId, title: $title}) {\n    projectV2 {\n      id\n      number\n      url\n      title\n      field(name: \"Status\") {\n        __typename\n        ... on ProjectV2SingleSelectField {\n          id\n          options {\n            id\n            name\n            color\n            description\n          }\n        }\n      }\n    }\n  }\n}\n\nmutation SetStatusOptions($fieldId: ID!, $options: [ProjectV2SingleSelectFieldOptionInput!]!) {\n  updateProjectV2Field(input: {fieldId: $fieldId, singleSelectOptions: $options}) {\n    projectV2Field {\n      __typename\n      ... on ProjectV2SingleSelectField {\n        id\n        options {\n          id\n          name\n        }\n      }\n    }\n  }\n}\n\nmutation LinkPlanRepository($projectId: ID!, $repositoryId: ID!) {\n  linkProjectV2ToRepository(\n    input: {projectId: $projectId, repositoryId: $repositoryId}\n  ) {\n    repository {\n      id\n    }\n  }\n}\n\nmutation CreatePlanIssue($repositoryId: ID!, $title: String!, $body: String!, $labelIds: [ID!], $parentIssueId: ID) {\n  createIssue(\n    input: {repositoryId: $repositoryId, title: $title, body: $body, labelIds: $labelIds, parentIssueId: $parentIssueId}\n  ) {\n    issue {\n      id\n      number\n      url\n    }\n  }\n}\n\nmutation AddPlanBlocker($issueId: ID!, $blockingIssueId: ID!) {\n  addBlockedBy(input: {issueId: $issueId, blockingIssueId: $blockingIssueId}) {\n    issue {\n      id\n    }\n  }\n}\n\nmutation AddPlanLabels($labelableId: ID!, $labelIds: [ID!]!) {\n  addLabelsToLabelable(input: {labelableId: $labelableId, labelIds: $labelIds}) {\n    clientMutationId\n  }\n}\n\nmutation AddPlanSubIssue($issueId: ID!, $subIssueId: ID!) {\n  addSubIssue(input: {issueId: $issueId, subIssueId: $subIssueId}) {\n    issue {\n      id\n    }\n  }\n}\n\nmutation CreatePlanLabel($repositoryId: ID!, $name: String!, $color: String!, $description: String!) {\n  createLabel(\n    input: {repositoryId: $repositoryId, name: $name, color: $color, description: $description}\n  ) {\n    label {\n      id\n    }\n  }\n}\n\nmutation AddPlanItem($projectId: ID!, $contentId: ID!) {\n  addProjectV2ItemById(input: {projectId: $projectId, contentId: $contentId}) {\n    item {\n      id\n    }\n  }\n}\n\nmutation SetPlanStatus($projectId: ID!, $itemId: ID!, $fieldId: ID!, $optionId: String!) {\n  updateProjectV2ItemFieldValue(\n    input: {projectId: $projectId, itemId: $itemId, fieldId: $fieldId, value: {singleSelectOptionId: $optionId}}\n  ) {\n    projectV2Item {\n      id\n    }\n  }\n}": types.CreatePlanProjectDocument,
    "query PlanOwnerIds($login: String!, $owner: String!, $name: String!) {\n  user(login: $login) {\n    id\n  }\n  repository(owner: $owner, name: $name) {\n    id\n  }\n}\n\nquery PlanProject($login: String!, $number: Int!) {\n  user(login: $login) {\n    projectV2(number: $number) {\n      id\n      number\n      url\n      title\n      field(name: \"Status\") {\n        __typename\n        ... on ProjectV2SingleSelectField {\n          id\n          options {\n            id\n            name\n          }\n        }\n      }\n    }\n  }\n}": types.PlanOwnerIdsDocument,
    "query PullRequestSnapshot($owner: String!, $name: String!, $number: Int!) {\n  repository(owner: $owner, name: $name) {\n    pullRequest(number: $number) {\n      number\n      title\n      isDraft\n      additions\n      deletions\n      changedFiles\n      updatedAt\n      url\n      headRefOid\n      headRefName\n      state\n      merged\n      mergeable\n      reviewDecision\n      commits(last: 1) {\n        nodes {\n          commit {\n            statusCheckRollup {\n              state\n              contexts(first: 100) {\n                nodes {\n                  __typename\n                  ... on CheckRun {\n                    databaseId\n                    name\n                    status\n                    conclusion\n                    detailsUrl\n                  }\n                  ... on StatusContext {\n                    context\n                    state\n                    targetUrl\n                  }\n                }\n              }\n            }\n          }\n        }\n      }\n      reviews(last: 50) {\n        nodes {\n          databaseId\n          state\n          body\n          submittedAt\n          author {\n            login\n          }\n          commit {\n            oid\n          }\n        }\n      }\n      reviewThreads(first: 100) {\n        nodes {\n          isResolved\n          comments(first: 1) {\n            nodes {\n              databaseId\n              author {\n                login\n              }\n              body\n              path\n              line\n              url\n            }\n          }\n        }\n      }\n      comments(last: 50) {\n        nodes {\n          author {\n            login\n          }\n          body\n          url\n        }\n      }\n    }\n  }\n}": types.PullRequestSnapshotDocument,
};

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "fragment IssueAncestors on Issue {\n  parent {\n    number\n    title\n    body\n    labels(first: 20) {\n      nodes {\n        name\n      }\n    }\n    issueType {\n      name\n    }\n    parent {\n      number\n      title\n      body\n      labels(first: 20) {\n        nodes {\n          name\n        }\n      }\n      issueType {\n        name\n      }\n      parent {\n        number\n        parent {\n          number\n          parent {\n            number\n          }\n        }\n      }\n    }\n  }\n}\n\nquery IssueParents($owner: String!, $name: String!, $number: Int!) {\n  repository(owner: $owner, name: $name) {\n    issue(number: $number) {\n      ...IssueAncestors\n    }\n  }\n}"): typeof import('./graphql.js').IssueAncestorsFragmentDoc;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "query IssueNodeId($owner: String!, $name: String!, $number: Int!) {\n  repository(owner: $owner, name: $name) {\n    issue(number: $number) {\n      id\n    }\n  }\n}\n\nquery IssueCreateRefs($owner: String!, $name: String!, $parent: Int!, $withParent: Boolean!) {\n  repository(owner: $owner, name: $name) {\n    id\n    labels(first: 100) {\n      nodes {\n        id\n        name\n      }\n    }\n    parent: issue(number: $parent) @include(if: $withParent) {\n      id\n    }\n  }\n}\n\nquery IssuePlan($owner: String!, $name: String!, $number: Int!) {\n  repository(owner: $owner, name: $name) {\n    owner {\n      id\n    }\n    issue(number: $number) {\n      id\n      number\n      title\n      body\n      labels(first: 20) {\n        nodes {\n          name\n        }\n      }\n      issueType {\n        name\n      }\n      parent {\n        number\n        title\n        body\n        labels(first: 20) {\n          nodes {\n            name\n          }\n        }\n        issueType {\n          name\n        }\n        parent {\n          number\n          title\n          body\n          labels(first: 20) {\n            nodes {\n              name\n            }\n          }\n          issueType {\n            name\n          }\n          parent {\n            number\n            parent {\n              number\n              parent {\n                number\n              }\n            }\n          }\n        }\n      }\n      projectItems(first: 20) {\n        nodes {\n          id\n          project {\n            id\n            number\n            owner {\n              id\n            }\n            field(name: \"Status\") {\n              __typename\n              ... on ProjectV2SingleSelectField {\n                id\n                options {\n                  id\n                  name\n                }\n              }\n            }\n          }\n          status: fieldValueByName(name: \"Status\") {\n            __typename\n            ... on ProjectV2ItemFieldSingleSelectValue {\n              name\n            }\n          }\n        }\n      }\n    }\n  }\n}"): typeof import('./graphql.js').IssueNodeIdDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "query PlanItems($login: String!, $number: Int!, $cursor: String) {\n  user(login: $login) {\n    projectV2(number: $number) {\n      items(first: 100, after: $cursor) {\n        pageInfo {\n          hasNextPage\n          endCursor\n        }\n        nodes {\n          status: fieldValueByName(name: \"Status\") {\n            __typename\n            ... on ProjectV2ItemFieldSingleSelectValue {\n              name\n            }\n          }\n          content {\n            __typename\n            ... on Issue {\n              number\n              title\n              url\n              state\n              updatedAt\n              repository {\n                name\n                owner {\n                  login\n                }\n              }\n              labels(first: 20) {\n                nodes {\n                  name\n                }\n              }\n              assignees(first: 10) {\n                nodes {\n                  login\n                }\n              }\n              issueType {\n                name\n              }\n              parent {\n                number\n                parent {\n                  number\n                  parent {\n                    number\n                  }\n                }\n              }\n              subIssuesSummary {\n                total\n                completed\n              }\n              blockedBy(first: 20) {\n                nodes {\n                  number\n                  state\n                }\n              }\n              closedByPullRequestsReferences(first: 10, includeClosedPrs: true) {\n                nodes {\n                  number\n                }\n              }\n            }\n          }\n        }\n      }\n    }\n  }\n}"): typeof import('./graphql.js').PlanItemsDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "mutation CreatePlanProject($ownerId: ID!, $title: String!) {\n  createProjectV2(input: {ownerId: $ownerId, title: $title}) {\n    projectV2 {\n      id\n      number\n      url\n      title\n      field(name: \"Status\") {\n        __typename\n        ... on ProjectV2SingleSelectField {\n          id\n          options {\n            id\n            name\n            color\n            description\n          }\n        }\n      }\n    }\n  }\n}\n\nmutation SetStatusOptions($fieldId: ID!, $options: [ProjectV2SingleSelectFieldOptionInput!]!) {\n  updateProjectV2Field(input: {fieldId: $fieldId, singleSelectOptions: $options}) {\n    projectV2Field {\n      __typename\n      ... on ProjectV2SingleSelectField {\n        id\n        options {\n          id\n          name\n        }\n      }\n    }\n  }\n}\n\nmutation LinkPlanRepository($projectId: ID!, $repositoryId: ID!) {\n  linkProjectV2ToRepository(\n    input: {projectId: $projectId, repositoryId: $repositoryId}\n  ) {\n    repository {\n      id\n    }\n  }\n}\n\nmutation CreatePlanIssue($repositoryId: ID!, $title: String!, $body: String!, $labelIds: [ID!], $parentIssueId: ID) {\n  createIssue(\n    input: {repositoryId: $repositoryId, title: $title, body: $body, labelIds: $labelIds, parentIssueId: $parentIssueId}\n  ) {\n    issue {\n      id\n      number\n      url\n    }\n  }\n}\n\nmutation AddPlanBlocker($issueId: ID!, $blockingIssueId: ID!) {\n  addBlockedBy(input: {issueId: $issueId, blockingIssueId: $blockingIssueId}) {\n    issue {\n      id\n    }\n  }\n}\n\nmutation AddPlanLabels($labelableId: ID!, $labelIds: [ID!]!) {\n  addLabelsToLabelable(input: {labelableId: $labelableId, labelIds: $labelIds}) {\n    clientMutationId\n  }\n}\n\nmutation AddPlanSubIssue($issueId: ID!, $subIssueId: ID!) {\n  addSubIssue(input: {issueId: $issueId, subIssueId: $subIssueId}) {\n    issue {\n      id\n    }\n  }\n}\n\nmutation CreatePlanLabel($repositoryId: ID!, $name: String!, $color: String!, $description: String!) {\n  createLabel(\n    input: {repositoryId: $repositoryId, name: $name, color: $color, description: $description}\n  ) {\n    label {\n      id\n    }\n  }\n}\n\nmutation AddPlanItem($projectId: ID!, $contentId: ID!) {\n  addProjectV2ItemById(input: {projectId: $projectId, contentId: $contentId}) {\n    item {\n      id\n    }\n  }\n}\n\nmutation SetPlanStatus($projectId: ID!, $itemId: ID!, $fieldId: ID!, $optionId: String!) {\n  updateProjectV2ItemFieldValue(\n    input: {projectId: $projectId, itemId: $itemId, fieldId: $fieldId, value: {singleSelectOptionId: $optionId}}\n  ) {\n    projectV2Item {\n      id\n    }\n  }\n}"): typeof import('./graphql.js').CreatePlanProjectDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "query PlanOwnerIds($login: String!, $owner: String!, $name: String!) {\n  user(login: $login) {\n    id\n  }\n  repository(owner: $owner, name: $name) {\n    id\n  }\n}\n\nquery PlanProject($login: String!, $number: Int!) {\n  user(login: $login) {\n    projectV2(number: $number) {\n      id\n      number\n      url\n      title\n      field(name: \"Status\") {\n        __typename\n        ... on ProjectV2SingleSelectField {\n          id\n          options {\n            id\n            name\n          }\n        }\n      }\n    }\n  }\n}"): typeof import('./graphql.js').PlanOwnerIdsDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "query PullRequestSnapshot($owner: String!, $name: String!, $number: Int!) {\n  repository(owner: $owner, name: $name) {\n    pullRequest(number: $number) {\n      number\n      title\n      isDraft\n      additions\n      deletions\n      changedFiles\n      updatedAt\n      url\n      headRefOid\n      headRefName\n      state\n      merged\n      mergeable\n      reviewDecision\n      commits(last: 1) {\n        nodes {\n          commit {\n            statusCheckRollup {\n              state\n              contexts(first: 100) {\n                nodes {\n                  __typename\n                  ... on CheckRun {\n                    databaseId\n                    name\n                    status\n                    conclusion\n                    detailsUrl\n                  }\n                  ... on StatusContext {\n                    context\n                    state\n                    targetUrl\n                  }\n                }\n              }\n            }\n          }\n        }\n      }\n      reviews(last: 50) {\n        nodes {\n          databaseId\n          state\n          body\n          submittedAt\n          author {\n            login\n          }\n          commit {\n            oid\n          }\n        }\n      }\n      reviewThreads(first: 100) {\n        nodes {\n          isResolved\n          comments(first: 1) {\n            nodes {\n              databaseId\n              author {\n                login\n              }\n              body\n              path\n              line\n              url\n            }\n          }\n        }\n      }\n      comments(last: 50) {\n        nodes {\n          author {\n            login\n          }\n          body\n          url\n        }\n      }\n    }\n  }\n}"): typeof import('./graphql.js').PullRequestSnapshotDocument;


export function graphql(source: string) {
  return (documents as any)[source] ?? {};
}
