import { readFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { build, transform, type Plugin } from "esbuild";

const here = (path: string) => fileURLToPath(new URL(path, import.meta.url));

/**
 * Zod re-exports every language's error messages as `locales`, which the MCP SDK's schemas keep in the bundle
 * (about 260 KB). The view never reads them and Zod's English messages come from locales/en.js, so the bundle
 * gets an empty `locales` instead.
 */
const withoutZodLocales: Plugin = {
  name: "without-zod-locales",
  setup(b) {
    b.onResolve({ filter: /\/locales\/index\.js$/ }, (args) => (/[/\\]zod[/\\]/.test(args.importer) ? { path: "zod-locales", namespace: "empty" } : undefined));
    b.onLoad({ filter: /.*/, namespace: "empty" }, () => ({ contents: "export {};", loader: "js" }));
  },
};

/** Where pnpm build:mcp-apps writes the bundled views, which the dashboard's MCP server serves. */
export const GENERATED_FILE = here("./views.generated.ts");

/** The views, each a page of its own: the name its root's data-view starts, its title and its constant in the generated file. */
export const VIEWS = [
  { name: "run-card", title: "Run card", constant: "RUN_CARD_HTML" },
  { name: "needs-you", title: "Needs you", constant: "NEEDS_YOU_HTML" },
  { name: "permission-card", title: "Permission card", constant: "PERMISSION_CARD_HTML" },
  { name: "question-card", title: "Question card", constant: "QUESTION_CARD_HTML" },
  { name: "plan-list", title: "Plan list", constant: "PLAN_LIST_HTML" },
] as const;

/** The stylesheets of the views, in order: the tokens and the run card, then the cards and the lists. */
const STYLES = ["./shared/base.css", "./shared/style.css"];

/** The views' one script (each view and the MCP Apps client they share) and their one stylesheet, minified. */
export type BuiltViews = { script: string; style: string };

/** Bundles the views' script and style, which every view's page inlines. */
export async function buildViews(): Promise<BuiltViews> {
  const [script, css] = await Promise.all([
    build({
      entryPoints: [here("./entry.ts")],
      bundle: true,
      write: false,
      format: "iife",
      platform: "browser",
      target: "es2022",
      minify: true,
      legalComments: "none",
      charset: "utf8",
      plugins: [withoutZodLocales],
    }),
    Promise.all(STYLES.map((file) => readFile(here(file), "utf8"))),
  ]);
  const style = await transform(css.join("\n"), { loader: "css", minify: true });
  // A script element ends at the first </script, wherever it is; inside JavaScript <\/ means the same.
  return { script: script.outputFiles[0]!.text.trim().replaceAll("</script", "<\\/script"), style: style.code.trim() };
}

/**
 * A view as one HTML document: the views' script and style inline, so a host renders it with no outside origins,
 * and the root naming the view to start.
 */
export const viewHtml = (view: { name: string; title: string }, { script, style }: BuiltViews) =>
  [
    "<!doctype html>",
    '<html lang="en">',
    `<head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${view.title}</title>`,
    `<style>${style}</style></head>`,
    `<body><div id="root" data-view="${view.name}"></div><script>${script}</script></body>`,
    "</html>",
    "",
  ].join("\n");

/**
 * viewHtml as views.generated.ts writes it, so the generated file holds the script and the style once. The bundle
 * test checks that each page it makes is viewHtml's.
 */
const GENERATED_PAGE = `const page = (name: string, title: string) =>
  [
    "<!doctype html>",
    '<html lang="en">',
    \`<head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>\${title}</title>\`,
    \`<style>\${STYLE}</style></head>\`,
    \`<body><div id="root" data-view="\${name}"></div><script>\${SCRIPT}</script></body>\`,
    "</html>",
    "",
  ].join("\\n");`;

/** The source of views.generated.ts: the script and the style once, and each view's page made from them. */
export const generatedSource = ({ script, style }: BuiltViews) =>
  [
    "// Generated by pnpm build:mcp-apps from src/mcp-apps. Do not edit; run it again after changing a view.",
    "// The views share one script and one stylesheet; each view's page names the view it starts.",
    `const SCRIPT = ${JSON.stringify(script)};`,
    `const STYLE = ${JSON.stringify(style)};`,
    GENERATED_PAGE,
    ...VIEWS.map((v) => `export const ${v.constant} = page(${JSON.stringify(v.name)}, ${JSON.stringify(v.title)});`),
    "",
  ].join("\n");

/** Where pnpm build:mcp-apps writes the sandbox proxy's script, which the proxy page inlines (see ./sandbox/proxy-page.ts). */
export const SANDBOX_GENERATED_FILE = here("./sandbox-proxy.generated.ts");

/** The sandbox proxy's script: ./sandbox/proxy.ts and its start, minified, safe inside a script element. */
export async function buildSandboxProxyScript(): Promise<string> {
  const script = await build({
    entryPoints: [here("./sandbox/entry.ts")],
    bundle: true,
    write: false,
    format: "iife",
    platform: "browser",
    target: "es2022",
    minify: true,
    legalComments: "none",
    charset: "utf8",
  });
  return script.outputFiles[0]!.text.trim().replaceAll("</script", "<\\/script");
}

/** The source of sandbox-proxy.generated.ts. */
export const sandboxGeneratedSource = (script: string) =>
  `// Generated by pnpm build:mcp-apps from src/mcp-apps/sandbox. Do not edit; run it again after changing the proxy.\nexport const SANDBOX_PROXY_SCRIPT = ${JSON.stringify(script)};\n`;
