import { readFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { build, transform, type Plugin } from "esbuild";

const here = (path: string) => fileURLToPath(new URL(path, import.meta.url));

/**
 * Zod re-exports every language's error messages as `locales`, which the MCP SDK's schemas keep in the bundle
 * (about 260 KB). The view never reads them and Zod's English messages come from locales/en.js, so the bundle
 * gets an empty `locales` instead.
 */
const withoutZodLocales: Plugin = {
  name: "without-zod-locales",
  setup(b) {
    b.onResolve({ filter: /\/locales\/index\.js$/ }, (args) => (/[/\\]zod[/\\]/.test(args.importer) ? { path: "zod-locales", namespace: "empty" } : undefined));
    b.onLoad({ filter: /.*/, namespace: "empty" }, () => ({ contents: "export {};", loader: "js" }));
  },
};

/** Where pnpm build:mcp-apps writes the bundled views, which the dashboard's MCP server serves. */
export const GENERATED_FILE = here("./run-card.generated.ts");

/**
 * The run card as one HTML document: its script (the view and the MCP Apps client) and its style inline, so a
 * host renders it with no outside origins. The dashboard serves the committed copy in run-card.generated.ts.
 */
export async function buildRunCardHtml(): Promise<string> {
  const [script, style] = await Promise.all([
    build({
      entryPoints: [here("./run-card/entry.ts")],
      bundle: true,
      write: false,
      format: "iife",
      platform: "browser",
      target: "es2022",
      minify: true,
      legalComments: "none",
      charset: "utf8",
      plugins: [withoutZodLocales],
    }),
    readFile(here("./run-card/style.css"), "utf8").then((css) => transform(css, { loader: "css", minify: true })),
  ]);
  // A script element ends at the first </script, wherever it is; inside JavaScript <\/ means the same.
  const js = script.outputFiles[0]!.text.trim().replaceAll("</script", "<\\/script");
  return [
    "<!doctype html>",
    '<html lang="en">',
    '<head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Run card</title>',
    `<style>${style.code.trim()}</style></head>`,
    `<body><div id="root"></div><script>${js}</script></body>`,
    "</html>",
    "",
  ].join("\n");
}

/** The source of run-card.generated.ts. */
export const generatedSource = (html: string) =>
  `// Generated by pnpm build:mcp-apps from src/mcp-apps/run-card. Do not edit; run it again after changing the view.\nexport const RUN_CARD_HTML = ${JSON.stringify(html)};\n`;

/** Where pnpm build:mcp-apps writes the sandbox proxy's script, which the proxy page inlines (see ./sandbox/proxy-page.ts). */
export const SANDBOX_GENERATED_FILE = here("./sandbox-proxy.generated.ts");

/** The sandbox proxy's script: ./sandbox/proxy.ts and its start, minified, safe inside a script element. */
export async function buildSandboxProxyScript(): Promise<string> {
  const script = await build({
    entryPoints: [here("./sandbox/entry.ts")],
    bundle: true,
    write: false,
    format: "iife",
    platform: "browser",
    target: "es2022",
    minify: true,
    legalComments: "none",
    charset: "utf8",
  });
  return script.outputFiles[0]!.text.trim().replaceAll("</script", "<\\/script");
}

/** The source of sandbox-proxy.generated.ts. */
export const sandboxGeneratedSource = (script: string) =>
  `// Generated by pnpm build:mcp-apps from src/mcp-apps/sandbox. Do not edit; run it again after changing the proxy.\nexport const SANDBOX_PROXY_SCRIPT = ${JSON.stringify(script)};\n`;
